# Generated by Django 2.2.7 on 2020-03-18 13:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone_number')),
                ('county', models.CharField(choices=[('BARINGO', 'BARINGO'), ('BOMET', 'BOMET'), ('BUNGOMA', 'BUNGOMA'), ('BUSIA', 'BUSIA'), ('ELGEYO MARAKWET', 'ELGEYO MARAKWET'), ('EMBU', 'EMBU'), ('GARISSA', 'GARISSA'), ('HOMA BAY', 'HOMA BAY'), ('ISIOLO', 'ISIOLO'), ('KAJIADO', 'KAJIADO'), ('KAKAMEGA', 'KAKAMEGA'), ('KERICHO', 'KERICHO'), ('KIAMBU', 'KIAMBU'), ('KILIFI', 'KILIFI'), ('KIRINYAGA', 'KIRINYAGA'), ('KISII', 'KISII'), ('KISUMU', 'KISUMU'), ('KITUI', 'KITUI'), ('KWALE', 'KWALE'), ('LAIKIPIA', 'LAIKIPIA'), ('LAMU', 'LAMU'), ('MACHAKOS', 'MACHAKOS'), ('MAKUENI', 'MAKUENI'), ('MANDERA', 'MANDERA'), ('MARSABIT', 'MARSABIT'), ('MERU', 'MERU'), ('MIGORI', 'MIGORI'), ('MOMBASA', 'MOMBASA'), ("MURANG'A", "MURANG'A"), ('NAIROBI', 'NAIROBI'), ('NAKURU', 'NAKURU'), ('NANDI', 'NANDI'), ('NAROK', 'NAROK'), ('NYAMIRA', 'NYAMIRA'), ('NYANDARUA', 'NYANDARUA'), ('NYERI', 'NYERI'), ('SAMBURU', 'SAMBURU'), ('SIAYA', 'SIAYA'), ('TAITA TAVETA', 'TAITA TAVETA'), ('TANA RIVER', 'TANA RIVER'), ('THARAKA NITHI', 'THARAKA NITHI'), ('TRANS NZOIA', 'TRANS NZOIA'), ('TURKANA', 'TURKANA'), ('UASIN GISHU', 'UASIN GISHU'), ('VIHIGA', 'VIHIGA'), ('WAJIR', 'WAJIR'), ('WEST POKOT', 'WEST POKOT')], max_length=50)),
                ('verification_code', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='CoronaSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Users')),
            ],
            options={
                'verbose_name': 'Symptom',
            },
        ),
    ]
