# Generated by Django 2.2.7 on 2020-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='arrived_recently',
            field=models.BooleanField(default=False),
        ),
    ]
