# Generated by Django 2.2.7 on 2020-03-19 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_users_arrived_recently'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronasymptoms',
            name='user_symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
